export const GET_SUBJECT_LIST = "GET_SUBJECT_LIST";
export const GET_SUBJECT_LIST_CHILD = "GET_SUBJECT_LIST_CHILD";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
